package registry

// GetCodeBuddyModels returns the available models for CodeBuddy (Tencent).
// These models are served through the copilot.tencent.com API.
func GetCodeBuddyModels() []*ModelInfo {
	now := int64(1748044800) // 2025-05-24
	return []*ModelInfo{
		{
			ID:                  "auto",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Auto",
			Description:         "Automatic model selection via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "glm-5v-turbo",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-5v Turbo",
			Description:         "GLM-5v Turbo via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "glm-5.1",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-5.1",
			Description:         "GLM-5.1 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "glm-5.0-turbo",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-5.0 Turbo",
			Description:         "GLM-5.0 Turbo via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "glm-5.0",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-5.0",
			Description:         "GLM-5.0 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "glm-4.7",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "GLM-4.7",
			Description:         "GLM-4.7 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "minimax-m2.7",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "MiniMax M2.7",
			Description:         "MiniMax M2.7 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "minimax-m2.5",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "MiniMax M2.5",
			Description:         "MiniMax M2.5 via CodeBuddy",
			ContextLength:       200000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "kimi-k2.5",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Kimi K2.5",
			Description:         "Kimi K2.5 via CodeBuddy",
			ContextLength:       256000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "kimi-k2.6",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Kimi K2.6",
			Description:         "Kimi K2.6 via CodeBuddy",
			ContextLength:       256000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "kimi-k2-thinking",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Kimi K2 Thinking",
			Description:         "Kimi K2 Thinking via CodeBuddy",
			ContextLength:       256000,
			MaxCompletionTokens: 32768,
			Thinking:            &ThinkingSupport{ZeroAllowed: true},
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "deepseek-v3-2-volc",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "DeepSeek V3.2 (Volc)",
			Description:         "DeepSeek V3.2 via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 32768,
			SupportedEndpoints:  []string{"/chat/completions"},
		},
		{
			ID:                  "hy3-preview",
			Object:              "model",
			Created:             now,
			OwnedBy:             "tencent",
			Type:                "codebuddy",
			DisplayName:         "Hy3 Preview",
			Description:         "Hy3 Preview via CodeBuddy",
			ContextLength:       128000,
			MaxCompletionTokens: 32768,
			Thinking:            &ThinkingSupport{ZeroAllowed: true},
			SupportedEndpoints:  []string{"/chat/completions"},
		},
	}
}
